// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yijogjeslljkyfvmxpst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlpam9namVzbGxqa3lmdm14cHN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1MDg0MTQsImV4cCI6MjA2MjA4NDQxNH0.AQZ0QZbtyJNG9KhQYU8KWrYTQA6F7iLpBSWxtbkJnGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);